### ISSUE TITLE
Letting somebody go checklist

### ISSUE THREAD

**Issue by ZachGoldberg** [ZachGoldberg/Startup-CTO-Handbook#25]
Consider adding a checklist of things for letting someone go

- [ ] Assuming the nautre of the underperformance is potentially correctable, give sufficient feedback and opportunity for the employee to improve
- [ ] Identify whether the role will be backfilled, and on what timing.
- [ ] Identify and plan for what will happen to in-progress work that might be dropped by this person's departure
- [ ] Work with HR on determining severance plan, taking into account tenure and other factors your company choses
- [ ] Work with HR to coordinate timing
- [ ] Have a communications plan for the rest of the team
- [ ] Have 1:1s with all of the let-go employee's coworkers / your direct reports to check in with them

and so on

**Comment by JilinJL** [comment]
Nice viewpoint,and what about a graduate with young ideas and learning skills(or learning among working) but lacking practical experience, how to determine the threshold for underperformance, related on the projects' subject we doing now?Practical development or cutting-edge innovation?

**Comment by koliber** [comment]
Underperformance is not absolute. I like the approach laid out by Refound's Accountability Dial. You mention the issue. You advance the conversation, set boundaries until it is clear that the person will not improve. Then it's time to consider letting someone go.

This is relative and should be dialed in to a specific situation.

**Comment by JilinJL** [comment]
> Underperformance is not absolute. I like the approach laid out by Refound's Accountability Dial. You mention the issue. You advance the conversation, set boundaries until it is clear that the person will not improve. Then it's time to consider letting someone go.
> 
> This is relative and should be dialed in to a specific situation. 

“_You advance the conversation, set boundaries until it is clear that the person will not improve._”.brief but impressive!
